question_data = [
    {"text": "Ramadan is the ninth month of the Islamic lunar calendar.", "answer": "True"},
    {"text": "Muslims fast from dawn to sunset during Ramadan.", "answer": "True"},
    {"text": "The pre-dawn meal before the fast begins is called Suhoor.", "answer": "True"},
    {"text": "The meal to break the fast at sunset is called Iftar.", "answer": "True"},
    {"text": "Fasting during Ramadan is obligatory for all adult Muslims, except for those who are ill, traveling, pregnant, breastfeeding, or menstruating.", "answer": "True"},
    {"text": "Laylat al-Qadr, also known as the Night of Decree, is believed to be the night when the Quran was first revealed to Prophet Muhammad (peace be upon him).", "answer": "True"},
    {"text": "Charity and giving to those in need (Zakat al-Fitr) is an important aspect of Ramadan.", "answer": "True"},
    {"text": "The last ten days of Ramadan are considered especially significant for seeking Laylat al-Qadr.", "answer": "True"},
    {"text": "The end of Ramadan is marked by the celebration of Eid al-Fitr.", "answer": "True"},
    {"text": "Muslims are encouraged to increase their worship, recitation of the Quran, and good deeds during Ramadan.", "answer": "True"},
    {"text": "Fasting during Ramadan includes abstaining from food, drink, smoking, and marital relations from dawn until sunset.", "answer": "True"},
    {"text": "Ramadan begins with the sighting of the new moon, as determined by Islamic authorities.", "answer": "True"},
    {"text": "In some Muslim-majority countries, it is a legal requirement to observe fasting during Ramadan.", "answer": "True"},
    {"text": "During Ramadan, Muslims are also encouraged to perform additional prayers called Tarawih at night.", "answer": "True"},
    {"text": "The practice of fasting during Ramadan is mentioned in the Quran.", "answer": "True"},
    {"text": "Muslims believe that fasting during Ramadan helps in spiritual growth, self-discipline, and empathy towards the less fortunate.", "answer": "True"},
    {"text": "Ramadan is considered a time for reflection, self-improvement, and strengthening one's relationship with Allah.", "answer": "True"},
    {"text": "The date of Eid al-Fitr, marking the end of Ramadan, is determined based on the sighting of the new moon.", "answer": "True"},
    {"text": "Muslims are encouraged to seek forgiveness, repentance, and reconciliation during Ramadan.", "answer": "True"},
    {"text": "The fast-breaking meal of Iftar often begins with eating dates and drinking water, following the tradition of Prophet Muhammad (peace be upon him).", "answer": "True"},
    {"text": "Ramadan serves as a reminder of the importance of gratitude, patience, and mindfulness in a Muslim's life.", "answer": "True"}
]